Application/Controllers/OrderController.cs
using Application.Areas.Identity.Data;
using Application.Models;
using Application.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.Diagnostics;
using Application.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.CodeAnalysis.CSharp.Syntax;


namespace Application.Controllers
{
    public class OrderController : Controller
    {
        private readonly ILogger<ProductsController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly CartService _cartService;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public OrderController(ILogger<ProductsController> logger, ApplicationDbContext context, CartService cartService, SignInManager<ApplicationUser> signInManager,UserManager<ApplicationUser> userManager )
        {
            _logger = logger;
            _context = context;
            _cartService = cartService; 
            _signInManager=signInManager;
            _userManager=userManager;
        }

        // Displays the good view of order history depending on the context
        public IActionResult OrderHistory(){
            
            if (!_signInManager.IsSignedIn(User)){
                return View("OrderHistoryNotLogged"); // Display the good view 
            }else{
                // Get the list of all orders made by the user
                List<Cart> cart = _cartService.GetUnactiveCart(_userManager.GetUserId(User));
                if (cart.Count==0){ // If no order has been made yet
                    return View("OrderHistoryNotYet");
                }else{
                    //Return the view OrderHistory passing the cart object as a model
                    return View("OrderHistory",cart);
                }
            }
        }
    }
}

Application/Controllers/ProductsController.cs
using Application.Areas.Identity.Data;
using Application.Models;
using Application.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.Diagnostics;
using Application.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http.Features;


namespace Application.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ILogger<ProductsController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly CartService _cartService;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ItemService _itemService;

        public ProductsController(ILogger<ProductsController> logger, ApplicationDbContext context, CartService cartService, SignInManager<ApplicationUser> signInManager,UserManager<ApplicationUser> userManager, ItemService itemService )
        {
            _logger = logger;
            _context = context;
            _cartService = cartService; // Inject the CartService
            _signInManager=signInManager;
            _userManager=userManager;
            _itemService=itemService;
        }

    

        // Return the view with the items according to the filters
        public async Task<IActionResult> Catalog(string category, decimal? minPrice, decimal? maxPrice)
        {
            //Get the list of all the items in the datable
            var productList= await _itemService.GetFilteredItemsAsync(category,minPrice,maxPrice);
            return View(productList);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        // Add an item to cart and send a response to the view to display a pop up
        [HttpPost]
        public JsonResult AddToCart(int id, string name, string description, decimal price, string imageUrl,string category){
            // Create an item object with the attributes sent by the view
            Item item = new Item{
                id = id,
                name = name,
                description = description,
                price = price,
                imageUrl = imageUrl,
                category=category};
            // Add this item to the cart associated to the user
            _cartService.AddItemToCart(_userManager.GetUserId(User), item);
            // Returns a JSON response indicating a success
            return Json(new {success=true});
        }

        // Display the good cart view depending on the context
        public IActionResult Cart(){
            if (!_signInManager.IsSignedIn(User)){ // User not logged in
                return View("CartNotLogged");
            }else{ // User logged in
                // Get the active cart associated to the user
                Cart cart = _cartService.GetActiveCart(_userManager.GetUserId(User));
                if(cart==null){ // User doesn't have a cart 
                    return View("CartLogged"); // Displays view wanted
                }else{ //User has a Cart
                    if(cart.cartItems.Count==0){ // No item in the cart
                        return View("CartLogged");
                    }else{
                        //return the view CartWithItems passing a cart object as a model
                        return View("CartWithItems",cart);
                    }
                }
            }
        }

        // Delete an item from the cart and displays the Cart views updated
        public IActionResult DeleteFromCart(int id, string name, string description, decimal price, string imageUrl, string category){
            // Instantiate an item with the attributes sent by the view
            Item item = new Item{
                id = id,
                name = name,
                description = description,
                price = price,
                imageUrl = imageUrl,
                category=category};
            //Remove item from the cart with this method
            _cartService.RemoveItemFromCart(_userManager.GetUserId(User), item);
            return Cart();
        }

        // Set the order to bought in the database 
        public IActionResult Buy(){
            _cartService.BuyCart(_userManager.GetUserId(User));
            return Cart();
        }
    }
}

Application/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Application</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Application.styles.css" asp-append-version="true" />
    @RenderSection("Style", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/MetaArt Market2.png" alt="MetaArt Market Logo" style="height: 40px;" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <!--<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>-->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Catalog">Catalog</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Cart">Cart</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="OrderHistory">Order History</a>
                        </li>

                        
                    </ul>
                    <partial name="_Loginpartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MadeInFrance team - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>